# Generated by Django 4.2.3 on 2023-12-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='qrcode',
        ),
    ]
