# Generated by Django 4.2.3 on 2023-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_remove_formmodel_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
