# Generated by Django 4.2.3 on 2023-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0003_formmodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
