# Generated by Django 5.0 on 2023-12-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0004_saveimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
