# Generated by Django 5.0 on 2023-12-28 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0005_alter_formmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='invite_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
