# Generated by Django 4.2.4 on 2023-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0006_formmodel_invite_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
