# Generated by Django 4.2.4 on 2023-12-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0007_formmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
