# Generated by Django 5.0 on 2023-12-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0009_formmodel_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='invite_by',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
